#Programa para compilar arquivos C++, o padrão é g++
CXX=g++
#Flags do compilador
CXXFLAGS=-std=c++11
#Dependências
#DEPS = ControleDeGastos.h Despesas.h  

main: main.cpp
	$(CXX) $(CXXFLAGS) main.cpp Relogio.cpp RelogioTeste.cpp -o main

#Apaga os arquivos objetos da pasta
limpar:
	rm -rf *.o

######################################
#Explicação
######################################
#regra: dependências 
# TAB comando  make 
# TAB comando
#
#criar:dependências 
# TAB comando  
# TAB comando
# 