#main: RestauranteCaseiro.cpp
#	g++ -std=c++11 Pedido.cpp MesaDeRestaurante.cpp RestauranteCaseiro.cpp -o RestauranteCaseiro
#	echo
#	./RestauranteCaseiro 

principal: main.cpp
	g++ -std=c++11 Pedido.cpp MesaDeRestaurante.cpp RestauranteCaseiro.cpp main.cpp -o main
	echo " "
	./main
	
clear:
	rm -rf *.o
	