#Programa para compilar arquivos C++, o padrão é g++
CXX=g++
#Flags do compilador
CXXFLAGS=-std=c++11
#Dependências
#DEPS = ControleDeGastos.h Despesas.h  

Despesas: Despesas.cpp
	$(CXX) $(CXXFLAGS) Despesas.cpp

#Despesas: Despesas.cpp
#	g++ -std=c++11 Despesas.cpp
